### ISSUE TITLE
Renaming a subdirectory in datasets and pushing reuploads all files

### ISSUE THREAD

**Issue by andrenmelo** [nimbo-sh/nimbo#16]
If you have pushed a subdirectory in your datasets folder, then rename it locally and push again, all files will be reuploaded. It seems to me that through [`aws mv`](https://docs.aws.amazon.com/cli/latest/reference/s3/mv.html) it should be possible to avoid this.

**Comment by noreferences** [comment]
Wont fix.

I was reimplementing `aws sync` with plain boto3 and I can say I understand why `aws sync` does not do this. The only way to prevent re-upload:
1. Keep in-memory what files are present locally and then what files are on S3
2. Do a big diff on paths and metadata to deduce what has been changed

This is a very expensive process, and given that we expect our users to use Nimbo with datasets that could potentially have millions of files - undesirable.

`aws mv` could indeed do a move, but we would still need to do a diff to deduce when to use `aws mv`.

As a workaround, it might be worth providing a utility to rename part of the path from Nimbo CLI. If we get more issues with renaming, we'll add it. If you have a specific use-case where you are frequently renaming directories, and this issue was not a one-off, let us know.
